CREATE TABLE applicants(
    applicant_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    group_id BIGINT NOT NULL,
    position_id BIGINT NOT NULL,
    applicant_name VARCHAR(20) NOT NULL,
    applicant_kana VARCHAR(20) NOT NULL,
    applicant_age INT NOT NULL,
    applicant_address VARCHAR(255) NOT NULL,
    applicant_email VARCHAR(255) NOT NULL,
    applicant_tel VARCHAR(20) NOT NULL,
    parent_name VARCHAR(20),
    is_student BOOLEAN NOT NULL DEFAULT TRUE,
    school_name VARCHAR(20),
    school_grade VARCHAR(10),
    school_class VARCHAR(10),
    cancel_status VARCHAR(30) NOT NULL DEFAULT 'NONE',
    applicant_note TEXT,
    staff_memo TEXT,
    application_number VARCHAR(6) NOT NULL UNIQUE,
    created_by VARCHAR(20),
    created_at TIMESTAMP NOT NULL,
    updated_by VARCHAR(20),
    updated_at TIMESTAMP NOT NULL,

    CONSTRAINT fk_applicants_group
        FOREIGN KEY (group_id)
            REFERENCES groups(group_id)
            ON DELETE CASCADE,

    CONSTRAINT fk_applicants_position
        FOREIGN KEY (position_id)
            REFERENCES positions(position_id)
            ON DELETE RESTRICT
);