spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  flyway:
    enabled: true
    locations: classpath:migration-postgresql
    table: FLYWAY_SCHEMA_HISTORY
    baseline-on-migrate: true
    baseline-version: 0