spring.application.name=backend

# 接続先設定（localhostの9092ポート経由でTCP接続）
spring.datasource.url=jdbc:h2:tcp://localhost:1521/opt/h2-data/testdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=work0915mh
spring.datasource.password=work0915mh

# H2コンソール設定（Spring Boot内蔵のものはオフにする、Docker側を使うため）
spring.h2.console.enabled=false

# JPA/Hibernateの設定（自動でテーブルを作成・更新する設定）
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.H2Dialect

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE