spring:
  application:
    name: backend
  main:
    banner-mode: off
  jpa:
    hibernate:
      ddl-auto: none
  flyway:
    enabled: true
    baseline-on-migrate: true
    table: FLYWAY_SCHEMA_HISTORY
  profiles:
    default: dev